language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  # Build database image.
  - docker build -t database db/.
  # Run the database image.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=pass -p 33060:3306 database
  # Build and install the application.
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # Clean any files.
  - mvn clean

# Job stages
jobs:
  include:
    # Unit test stage.
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      # Tell Maven to run the unit tests.
      script: mvn test -Dtest=com.napier.sem.AppTest

    - stage: integration_tests
      jdk: oraclejdk11
      # Tell Maven to run the integration tests.
      script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
    - stage: GitHub Release
      # We don't want to install
      install: skip
      # We will build the JAR
      jdk: oraclejdk11
      script:
          - echo "Deploying to GitHub Releases"
          # Package (build) the JAR
          - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
          # Set up git user name and tag this commit
          - git config --local user.name "Min Hein Htet"
          - git config --local user.email "40414300@live.napier.ac.uk"
          # Create temporary tag from date and Git log.
          - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
          # Set tag
          - git tag $TRAVIS_TAG
      deploy:
          provider: releases
          # This is the token we set before
          api_key: $GITHUB_OAUTH_TOKEN
          # Copy built JAR file to release.  JAR built in $TRAVIS_BUILD_DIR/target
          file: $TRAVIS_BUILD_DIR/target/seMethods.jar
          skip_cleanup: true


stages:
  - unit tests
  - integration_tests
  - name: GitHub Release
    if: branch = master

after_success:
  # Push code coverage data to codecov.
  - bash <(curl -s https://codecov.io/bash)
