language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  # Build database image.
  - docker build -t database db/.
  # Run the database image.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=pass -p 33060:3306 database
  # Build and install the application.
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # Clean any files.
  - mvn clean

# Job stages
jobs:
  include:
    # Unit test stage.
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      # Tell Maven to run the unit tests.
      script: mvn test -Dtest=com.napier.sem.AppTest

    - stage: integration_tests
      jdk: oraclejdk11
      # Tell Maven to run the integration tests.
      script: mvn test -Dtest=com.napier.sem.AppIntegrationTest

stages:
  - unit tests
  - integration_tests

after_success:
  # Push code coverage data to codecov.
  - bash <(curl -s https://codecov.io/bash)
