language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  # Build and install the application.
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # Clean any files.
  - mvn clean

# Job stages
jobs:
  include:
    - stage: Integration_test
    script:
          - docker build -t db db/
          - docker run --rm -d -p 3306:3306 db
          - mvn test -Dtest=com.napier.sem.AppIntegrationTest

stages:
  - integration_test
